version: '3.8'

services:
  db:
    image: postgres:17.4
    container_name: win-postgres
    environment:
      POSTGRES_DB: win_dt b
      POSTGRES_USER: win_user
      POSTGRES_PASSWORD: win_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: win-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
